# CAISO Data Fetcher
This notebook will us the pycaiso python library to collect forecasted caiso data

In [29]:
import pycaiso.oasis
#! pip install pycaiso

In [30]:
# example from documentation
from pycaiso.oasis import Node
from datetime import datetime
import pandas as pd

# select pnode

cj = Node("CAPTJACK_5_N003")

# create dataframe with LMPS from arbitrary period (30 day maximum). 

cj_lmps = cj.get_lmps(datetime(2021, 1, 1), datetime(2021, 1, 2))

print(cj_lmps.head())

       INTERVALSTARTTIME_GMT        INTERVALENDTIME_GMT     OPR_DT  OPR_HR  \
0  2021-01-01T08:00:00-00:00  2021-01-01T09:00:00-00:00 2021-01-01       1
1  2021-01-01T08:00:00-00:00  2021-01-01T09:00:00-00:00 2021-01-01       1
2  2021-01-01T08:00:00-00:00  2021-01-01T09:00:00-00:00 2021-01-01       1
3  2021-01-01T08:00:00-00:00  2021-01-01T09:00:00-00:00 2021-01-01       1
4  2021-01-01T09:00:00-00:00  2021-01-01T10:00:00-00:00 2021-01-01       2

   OPR_INTERVAL      NODE_ID_XML          NODE_ID             NODE  \
0             0  CAPTJACK_5_N003  CAPTJACK_5_N003  CAPTJACK_5_N003
1             0  CAPTJACK_5_N003  CAPTJACK_5_N003  CAPTJACK_5_N003
2             0  CAPTJACK_5_N003  CAPTJACK_5_N003  CAPTJACK_5_N003
3             0  CAPTJACK_5_N003  CAPTJACK_5_N003  CAPTJACK_5_N003
4             0  CAPTJACK_5_N003  CAPTJACK_5_N003  CAPTJACK_5_N003

  MARKET_RUN_ID LMP_TYPE XML_DATA_ITEM    PNODE_RESMRID GRP_TYPE  POS  \
0           DAM      LMP       LMP_PRC  CAPTJACK_5_N003      ALL    1
1           DAM      MCC  LMP_CONG_PRC  CAPTJACK_5_N003      ALL    1
2           DAM      MCE   LMP_ENE_PRC  CAPTJACK_5_N003      ALL    1
3           DAM      MCL  LMP_LOSS_PRC  CAPTJACK_5_N003      ALL    1
4           DAM      LMP       LMP_PRC  CAPTJACK_5_N003      ALL    1

         MW  GROUP
0  33.32310      1
1   0.00000      2
2  34.68627      3
3  -1.36317      4
4  31.51635      1

In [31]:
from pycaiso.oasis import SystemDemand
sd = SystemDemand()

In [32]:
df = sd.get_demand_forecast(start=datetime(2024, 3, 23), end=datetime(2024, 3, 25))

In [33]:
data_dict = {'INTERVALSTARTTIME_GMT':'the start of the forecast',
             'INTERVALENDTIME_GMT':'the end time of the forecast',
             'LOAD_TYPE':'no idea what this is',
             'OPR_DT':'no idea',
             'OPR_HR':'operating hour?',
             'OPR_INTERVAL':'some interval time',
             'MARKET_RUN_ID':'2DA = two day ahead, DAM= day ahead market, 7DA = seven day ahead forecast', 
             'TAC_AREA_NAME':'Transmission access charge. It is the area in california where the forecast occurs. PGE = Bay area, SCE = LA, SDGE = San Diego. From Claude - A transmission access charge (TAC) is a fee charged by transmission owners and operators, such as PG&E (Pacific Gas and Electric Company), to recover the costs associated with operating and maintaining their high-voltage transmission system.', 
             'LABEL':'same as Market Run ID',
             'XML_DATA_ITEM':'System forecast for the MARKET RUN ID, same as Market run id', 
             'POS':'no idea', 
             'MW':'Megawatts?', 
             'EXECUTION_TYPE':'Same as Market Run ID', 
             'GROUP':'subset of TAC? Should be some kind of region code'}
df

,INTERVALSTARTTIME_GMT,INTERVALENDTIME_GMT,LOAD_TYPE,OPR_DT,OPR_HR,OPR_INTERVAL,MARKET_RUN_ID,TAC_AREA_NAME,LABEL,XML_DATA_ITEM,POS,MW,EXECUTION_TYPE,GROUP
0,2024-03-23T17:00:00-00:00,2024-03-23T18:00:00-00:00,2,2024-03-23,11,0,2DA,AVA,Demand Forecast 2-Day Ahead,SYS_FCST_2DA_MW,1.8,1196.51,2DA,1
1,2024-03-23T18:00:00-00:00,2024-03-23T19:00:00-00:00,2,2024-03-23,12,0,2DA,AVA,Demand Forecast 2-Day Ahead,SYS_FCST_2DA_MW,1.8,1186.79,2DA,1
2,2024-03-23T15:00:00-00:00,2024-03-23T16:00:00-00:00,2,2024-03-23,9,0,2DA,AVA,Demand Forecast 2-Day Ahead,SYS_FCST_2DA_MW,1.8,1165.87,2DA,1
3,2024-03-23T10:00:00-00:00,2024-03-23T11:00:00-00:00,2,2024-03-23,4,0,2DA,AVA,Demand Forecast 2-Day Ahead,SYS_FCST_2DA_MW,1.8,881.54,2DA,1
4,2024-03-24T04:00:00-00:00,2024-03-24T05:00:00-00:00,2,2024-03-23,22,0,2DA,AVA,Demand Forecast 2-Day Ahead,SYS_FCST_2DA_MW,1.8,1133.86,2DA,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25786,2024-03-24T14:05:00-00:00,2024-03-24T14:10:00-00:00,0,2024-03-24,8,2,RTM,WALCDSW,RTM 5Min Load Forecast,SYS_FCST_5MIN_MW,5.8,169.36,RTD,414
25787,2024-03-24T15:50:00-00:00,2024-03-24T15:55:00-00:00,0,2024-03-24,9,11,RTM,WALCDSW,RTM 5Min Load Forecast,SYS_FCST_5MIN_MW,5.8,169.67,RTD,414
25788,2024-03-24T15:55:00-00:00,2024-03-24T16:00:00-00:00,0,2024-03-24,9,12,RTM,WALCDSW,RTM 5Min Load Forecast,SYS_FCST_5MIN_MW,5.8,170.12,RTD,414
25789,2024-03-24T16:05:00-00:00,2024-03-24T16:10:00-00:00,0,2024-03-24,10,2,RTM,WALCDSW,RTM 5Min Load Forecast,SYS_FCST_5MIN_MW,5.8,172.68,RTD,414
25790,2024-03-24T17:25:00-00:00,2024-03-24T17:30:00-00:00,0,2024-03-24,11,6,RTM,WALCDSW,RTM 5Min Load Forecast,SYS_FCST_5MIN_MW,5.8,158.90,RTD,414

In [34]:
df['TAC_AREA_NAME'].value_counts()

TAC_AREA_NAME
AVA           741
SRP           741
PGE-TAC       741
PNM           741
PSEI          741
SCE-TAC       741
SCL           741
SDGE-TAC      741
TEPC          741
PACW          741
TIDC          741
TPWR          741
VEA-TAC       741
WALC          741
WALCAEPCO     741
WALCDSW       741
PGE           741
PACE          741
AVRN          741
BANCWASN      741
AZPS          741
BANC          741
BANCMID       741
BANCRDNG      741
BANCRSVL      741
BANCSMUD      741
BPAT          741
NWMT          741
CA ISO-TAC    741
EPE           741
IPCO          741
LADWP         741
MWD-TAC       741
NEVP          741
BCHA          597
Name: count, dtype: int64

In [35]:
cols = ['OPR_DT', 'OPR_HR','TAC_AREA_NAME', 'MW']
df.loc[(df['MARKET_RUN_ID'] == '7DA') & (df['TAC_AREA_NAME'] == 'AVA') , cols].sort_values(by=['OPR_DT', 'OPR_HR'])

           OPR_DT  OPR_HR TAC_AREA_NAME       MW
833    2024-03-23       1           AVA  1004.53
836    2024-03-23       2           AVA   984.95
830    2024-03-23       3           AVA   978.39
834    2024-03-23       4           AVA   984.54
835    2024-03-23       5           AVA  1008.80
819    2024-03-23       6           AVA  1061.97
825    2024-03-23       7           AVA  1142.90
837    2024-03-23       8           AVA  1219.26
826    2024-03-23       9           AVA  1265.92
821    2024-03-23      10           AVA  1275.16
831    2024-03-23      11           AVA  1258.47
827    2024-03-23      12           AVA  1229.18
838    2024-03-23      13           AVA  1196.01
822    2024-03-23      14           AVA  1165.01
820    2024-03-23      15           AVA  1138.54
832    2024-03-23      16           AVA  1127.65
839    2024-03-23      17           AVA  1129.87
816    2024-03-23      18           AVA  1149.81
828    2024-03-23      19           AVA  1164.20
823    2024-03-23      20           AVA  1201.04
817    2024-03-23      21           AVA  1189.85
829    2024-03-23      22           AVA  1146.62
824    2024-03-23      23           AVA  1087.67
818    2024-03-23      24           AVA  1032.55
17558  2024-03-24       1           AVA  1009.27
17544  2024-03-24       2           AVA   992.82
17551  2024-03-24       3           AVA   990.59
17567  2024-03-24       4           AVA   999.33
17556  2024-03-24       5           AVA  1022.44
17552  2024-03-24       6           AVA  1070.06
17546  2024-03-24       7           AVA  1143.92
17545  2024-03-24       8           AVA  1216.30
17562  2024-03-24       9           AVA  1262.94
17547  2024-03-24      10           AVA  1272.82
17561  2024-03-24      11           AVA  1256.48
17548  2024-03-24      12           AVA  1233.19
17553  2024-03-24      13           AVA  1209.45
17549  2024-03-24      14           AVA  1184.36
17565  2024-03-24      15           AVA  1159.68
17554  2024-03-24      16           AVA  1152.94
17555  2024-03-24      17           AVA  1166.00
17550  2024-03-24      18           AVA  1200.55
17559  2024-03-24      19           AVA  1221.09
17566  2024-03-24      20           AVA  1262.97
17564  2024-03-24      21           AVA  1251.03
17560  2024-03-24      22           AVA  1191.64
17557  2024-03-24      23           AVA  1110.63
17563  2024-03-24      24           AVA  1045.17

In [40]:
import importlib
importlib.reload(pycaiso.oasis)
from pycaiso.oasis import SystemDemand
sd = SystemDemand()
df = sd.get_wind_and_solar_forecast(start=datetime(2024, 3, 23), end=datetime(2024, 3, 25))
df.head()

<Response [200]>

,OPR_DT,OPR_HR,OPR_INTERVAL,INTERVALSTARTTIME_GMT,INTERVALENDTIME_GMT,TRADING_HUB,RENEWABLE_TYPE,LABEL,XML_DATA_ITEM,MARKET_RUN_ID_POS,RENEW_POS,MW,MARKET_RUN_ID,GROUP
0,2024-03-23,11,0,2024-03-23T17:00:00-00:00,2024-03-23T18:00:00-00:00,NP15,Solar,Renewable Forecast Day Ahead,RENEW_FCST_DA_MW,1,2,1292.22,DAM,1
1,2024-03-23,24,0,2024-03-24T06:00:00-00:00,2024-03-24T07:00:00-00:00,NP15,Solar,Renewable Forecast Day Ahead,RENEW_FCST_DA_MW,1,2,0.00,DAM,1
2,2024-03-23,10,0,2024-03-23T16:00:00-00:00,2024-03-23T17:00:00-00:00,NP15,Solar,Renewable Forecast Day Ahead,RENEW_FCST_DA_MW,1,2,1171.59,DAM,1
3,2024-03-23,15,0,2024-03-23T21:00:00-00:00,2024-03-23T22:00:00-00:00,NP15,Solar,Renewable Forecast Day Ahead,RENEW_FCST_DA_MW,1,2,1098.07,DAM,1
4,2024-03-23,9,0,2024-03-23T15:00:00-00:00,2024-03-23T16:00:00-00:00,NP15,Solar,Renewable Forecast Day Ahead,RENEW_FCST_DA_MW,1,2,817.68,DAM,1

# params used by pycaiso library
not needed, unless they are neeeded, ya know?

In [ ]:
params: Dict[str, Any] = {
        "queryname": QUERY_MAPPING[market],
        "market_run_id": market,
        "startdatetime": oasis._get_UTC_string(start),
        "enddatetime": oasis._get_UTC_string(end),
        "version": 1,
        "node": node,
        "resultformat": 6,
    }

# testing crap down below

In [16]:
import datetime as dt
import urllib
d1 = dt.date(2024,3,20)
d2 = dt.date(2024,3,21) # dt.date.today()
days = [d1 + dt.timedelta(days=x) for x in range((d2-d1).days + 1)]
# specify url based on file types available
file_types = ['demand', 'netdemand', 'fuelsource', 'storage', 'co2', 'rtm_forecast']
url_format = "http://www.caiso.com/outlook/SP/History/%s/%s.csv"

In [17]:
day = days[0]
file_type = 'demand'
url = url_format % (day.strftime("%Y%m%d"), file_type)
file = urllib.request.urlopen(url)
file

In [18]:
pd.read_csv(file)

,Time,Day ahead forecast,Hour ahead forecast,Current demand,Demand response
0,00:00,21866,20755,20680,NaN
1,00:05,20945,20755,20803,NaN
2,00:10,20945,20755,20864,NaN
3,00:15,20945,20755,20764,NaN
4,00:20,20945,20679,20722,NaN
...,...,...,...,...,...
284,23:40,21859,21301,21323,NaN
285,23:45,21859,21301,21223,NaN
286,23:50,21859,21089,21095,NaN
287,23:55,21859,21089,21006,NaN
288,00:00,21859,21089,20909,NaN

In [ ]:
"http://oasis.caiso.com/mrtu-oasis/SingleZip?queryname=AS_REQ&startdate=20061002&enddate=20061002&market_run_id=DAM&as_type=ALL&as_region=ALL"

In [20]:
url_format = "http://oasis.caiso.com/mrtu-oasis/SingleZip?queryname=SLD_FCST&market_run_id=DAM&startdate=%s&enddate=%s"
url = url_format % (d1.strftime("%Y%m%d"), d2.strftime("%Y%m%d"))
print(url)
file = urllib.request.urlopen(url)
file

http://oasis.caiso.com/mrtu-oasis/SingleZip?queryname=SLD_FCST&market_run_id=DAM&startdate=20240320&enddate=20240321

HTTPError: HTTP Error 404: Not Found

In [ ]:
http://oasis.caiso.com/oasisapi/SingleZip?

In [28]:
url = "http://oasismap.caiso.com/oasisapi/SingleZip?queryname=AS_REQ&startdatetime=20240919T07:00-0000&enddatetime=20240920T07:00-0000&market_run_id=DAM&version=1&as_type=ALL&as_region=ALL"
file = urllib.request.urlopen(url)
file

In [33]:
dir(file)
file.peek()

b''